# Generated by Django 5.0.4 on 2024-04-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='article snippet...', max_length=255),
        ),
    ]
