# Generated by Django 5.0.4 on 2024-05-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0007_post_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippets',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
